language: go
sudo: false
os:
  - linux
  - osx
go:
  - 1.21.0
matrix:
  exclude:
     [go: '1.21.x']
env:
 global:
   - GOPROXY=https://gocenter.io,https://goproxy.io,https://goproxy.cn,direct
before_install:
  - chmod +x .travis.gofmt.sh
  - chmod +x .travis.gotest.sh
script:
  - ./.travis.gofmt.sh
  - ./.travis.gotest.sh
